version: '1.9'

services:
#  mongo:
#    image: mongo:latest
#    container_name: mongodb
#    restart: always
#    ports:
#      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=user
#      - MONGO_INITDB_ROOT_PASSWORD=pass
#      - MONGO_INITDB_DATABASE=mychat
#    volumes:
#      - 'm321_mongodb:/data/db'
#      - ./mongo-init:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - 'm321_mongodb:/data/db'

  webserver:
    depends_on:
      - mongo
    container_name: server
    image: dominicstreit/321:latest
    ports:
      - 3000:3000

volumes:
  m321_mongodb:
