version: '1.9'

services:
  mongo:
    image: 'mongo:3.4.1'
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'm321_mongodb:/data/db'

  webserver:
    depends_on:
      - mongo
    container_name: server
    image: dominicstreit/321:latest
    ports:
      - 3000:3000

volumes:
  m321_mongodb:
